DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS daily_steps CASCADE;
DROP TABLE IF EXISTS image_store CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS challenges CASCADE;
DROP TABLE IF EXISTS user_challenges CASCADE;
-- DROP TABLE IF EXISTS runs CASCADE;
