name: Build and Test Backend
run-name: 🚀 Pipeline for Branch ${{ github.ref_name }}

on:
  pull_request:
      paths:
      - 'rocket-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Build
        working-directory: rocket-backend
        run: go build -v ./...

      - name: Test with the Go CLI
        working-directory: rocket-backend
        run: go test ./...
